export const DEFAULTS = [
"Tomatoes, basil, and mozzarella",
"Avocado, lime, and cilantro",
"Peanut butter, soy sauce, and honey",
"Lemon, garlic, and olive oil",
"Bacon, lettuce, and tomato",
"Ginger, garlic, and soy sauce",
"Cinnamon, nutmeg, and cloves",
"Blueberries, honey, and yogurt",
"Parmesan cheese, garlic, and breadcrumbs",
"Apples, cinnamon, and caramel",
"Chicken, lemon, and rosemary",
"Black beans, corn, and cilantro",
"Cucumber, mint, and feta cheese",
"Garlic, onion, and bell pepper",
"Beef, mushrooms, and red wine",
"Sweet potato, cinnamon, and nutmeg",
"Salmon, dill, and lemon",
"Shrimp, garlic, and butter",
"Spinach, feta cheese, and sun-dried tomatoes",
"Pork, apple, and sage",
"Cherry tomatoes, garlic, and balsamic vinegar",
"Asparagus, lemon, and Parmesan cheese",
"Broccoli, garlic, and olive oil",
"Cauliflower, curry powder, and coconut milk",
"Carrots, ginger, and honey",
"Strawberries, balsamic vinegar, and black pepper",
"Green beans, almonds, and lemon zest",
"Quinoa, black beans, and avocado",
"Tuna, mayonnaise, and celery",
"Cilantro, lime, and jalapeno",
"Zucchini, garlic, and Parmesan cheese",
"Chocolate, hazelnut, and cream",
"Pesto, tomato, and mozzarella",
"Potato, cheddar cheese, and bacon",
"Cornmeal, flour, and buttermilk",
"Basil, tomato, and garlic",
"Artichoke, lemon, and garlic",
"Ham, Swiss cheese, and mustard",
"Figs, prosciutto, and balsamic vinegar",
"Cranberries, orange, and pecans",
"Blackberry, thyme, and goat cheese",
"Lemon, honey, and ginger",
"Cinnamon, sugar, and butter",
"Brown sugar, butter, and vanilla extract",
"Garlic, lemon, and olive oil",
"Tomato, onion, and cilantro",
"Chicken, mushroom, and thyme",
"Sausage, onion, and bell pepper",
"Cabbage, onion, and bacon",
"Eggplant, tomato, and mozzarella",
"Cherry, almond, and chocolate",
"Pineapple, coconut, and rum",
"Caramel, sea salt, and chocolate",
"Peanut butter, banana, and honey",
"Raspberry, lemon, and white chocolate",
"Maple syrup, bacon, and pecans",
"Sesame oil, soy sauce, and honey",
"Garlic, ginger, and hoisin sauce",
"Lemon, garlic, and oregano",
"Chili powder, cumin, and garlic",
"Cheddar cheese, jalapeno, and bacon",
"Scallions, garlic, and soy sauce",
"Turmeric, ginger, and coconut milk",
"Garlic, lemon, and cumin",
"Black pepper, thyme, and garlic",
"Ginger, garlic, and chili paste",
"Beef, onion, and green pepper",
"Bell pepper, onion, and garlic",
"Green onions, garlic, and ginger",
"Carrots, garlic, and ginger",
"Chicken, onion, and garlic",
"Cumin, coriander, and paprika",
"Apple, cinnamon, and nutmeg",
"Cinnamon, cloves, and ginger",
"Apple, cranberry, and walnut",
"Banana, peanut butter, and chocolate",
"Blueberry, lemon, and cream cheese",
"Lemon, garlic, and parsley",
"Sage, onion, and thyme",
"Potato, leek, and bacon",
"Butternut squash, sage, and brown butter",
"Fennel, orange, and olive oil",
"Pear, blue cheese, and arugula",
"Pecan, maple, and bourbon",
"Raspberry, brie, and basil",
"Coconut, lime, and cilantro",
"Cherry, almond, and cream cheese",
"Sweet potato, pecan, and marshmallow",
"Prosciutto, melon, and mint",
"Parmesan cheese, lemon, and black pepper",
"Green apple, cheddar cheese, and mustard",
"Feta cheese, cucumber, and red onion",
"Corn, tomato, and basil",
"Peach, basil, and balsamic vinegar",
"Honey, mustard, and thyme",
"Cucumber, avocado, and lime",
"Grapefruit, avocado, and shrimp",
"Lemon, basil, and pine nuts",
"Cherry tomato, mozzarella, and basil pesto.",
"Salmon, avocado, and wasabi",
"Quinoa, roasted vegetables, and tahini",
"Blackberry, mint, and lime",
"Cranberry, orange, and ginger",
"Grape, almond, and blue cheese",
"Radish, cucumber, and feta cheese",
"Caprese salad: tomato, mozzarella, and basil",
"Egg, spinach, and feta cheese",
"Lamb, rosemary, and garlic",
"Pear, walnut, and blue cheese",
"Brussels sprouts, bacon, and apple cider vinegar",
"Pesto, pine nuts, and Parmesan cheese",
"Beetroot, goat cheese, and arugula",
"Mushroom, truffle, and Parmesan cheese",
"Green beans, shallot, and bacon",
"Pork, apple, and cinnamon",
"Red pepper, tomato, and basil",
"Sweet potato, kale, and chorizo",
"Tomato, feta cheese, and olives",
"Tuna, avocado, and sesame seeds",
"Zucchini, feta cheese, and mint",
"Blueberry, lemon, and thyme",
"Coconut, lime, and mango",
"Apricot, almond, and honey",
"Balsamic vinegar, olive oil, and garlic",
"Cherry, lime, and tequila",
"Mango, lime, and chili",
"Blueberry, banana, and chia seeds",
"Lemon, honey, and rosemary",
"Cucumber, celery, and lemon",
"Feta cheese, cherry tomato, and oregano",
"Ginger, honey, and lemon",
"Pineapple, jalapeno, and cilantro",
"Fennel, orange, and pomegranate",
"Balsamic vinegar, olive oil, and honey",
"Parmesan cheese, garlic, and lemon zest",
"Ricotta cheese, basil, and lemon",
"Butternut squash, sage, and nutmeg",
"Gouda cheese, apple, and rosemary",
"Pistachio, honey, and goat cheese",
"Radicchio, pear, and gorgonzola",
"Red onion, goat cheese, and arugula",
"Watermelon, feta cheese, and mint",
"Carrot, ginger, and orange",
"Banana, chocolate, and hazelnut",
"Blueberry, lemon, and ricotta cheese",
"Chocolate, raspberry, and cream",
"Mango, coconut, and lime",
"Pomegranate, orange, and mint",
"Sweet potato, black beans, and avocado",
"Lemon, olive oil, and parsley",
"Peach, basil, and goat cheese",
"Shrimp, garlic, and lemon",
"Strawberry, basil, and balsamic vinegar",
"Cranberry, walnut, and blue cheese",
"Lemon, thyme, and garlic",
"Apple, cheddar cheese, and rosemary",
"Caramel, apple, and cinnamon",
"Carrot, raisin, and walnut",
"Cauliflower, tahini, and lemon",
"Cherry, almond, and vanilla",
"Chickpea, cucumber, and feta cheese",
"Orange, carrot, and ginger",
"Pecan, goat cheese, and honey",
"Pear, prosciutto, and arugula",
"Roasted vegetables, quinoa, and feta cheese"
]
