export const EXAMPLES = [
  "Apple, cheddar cheese, and rosemary",
  "Apple, cinnamon, and nutmeg",
  "Apple, cranberry, and walnut",
  "Apples, cinnamon, and caramel",
  "Apricot, almond, and honey",
  "Artichoke, lemon, and garlic",
  "Asparagus, lemon, and Parmesan cheese",
  "Avocado, lime, and cilantro",
  "Bacon, lettuce, and tomato",
  "Balsamic vinegar, olive oil, and garlic",
  "Balsamic vinegar, olive oil, and honey",
  "Banana, chocolate, and hazelnut",
  "Banana, peanut butter, and chocolate",
  "Basil, tomato, and garlic",
  "Beef, onion, and green pepper",
  "Beetroot, goat cheese, and arugula",
  "Bell pepper, onion, and garlic",
  "Black beans, corn, and cilantro",
  "Black pepper, thyme, and garlic",
  "Blackberry, mint, and lime",
  "Blackberry, thyme, and goat cheese",
  "Blueberries, honey, and yogurt",
  "Blueberry, banana, and chia seeds",
  "Blueberry, lemon, and cream cheese",
  "Blueberry, lemon, and ricotta cheese",
  "Blueberry, lemon, and thyme",
  "Broccoli, garlic, and olive oil",
  "Brown sugar, butter, and vanilla extract",
  "Brussels sprouts, bacon, and apple cider vinegar",
  "Butternut squash, sage, and brown butter",
  "Butternut squash, sage, and nutmeg",
  "Cabbage, onion, and bacon",
  "Caprese salad: tomato, mozzarella, and basil",
  "Caramel, apple, and cinnamon",
  "Caramel, sea salt, and chocolate",
  "Carrot, ginger, and orange",
  "Carrot, raisin, and walnut",
  "Carrots, garlic, and ginger",
  "Carrots, ginger, and honey",
  "Cauliflower, curry powder, and coconut milk",
  "Cauliflower, tahini, and lemon",
  "Cheddar cheese, jalapeno, and bacon",
  "Cherry tomato, mozzarella, and basil pesto.",
  "Cherry tomatoes, garlic, and balsamic vinegar",
  "Cherry, almond, and chocolate",
  "Cherry, almond, and cream cheese",
  "Cherry, almond, and vanilla",
  "Chicken, lemon, and rosemary",
  "Chicken, mushroom, and thyme",
  "Chicken, onion, and garlic",
  "Chickpea, cucumber, and feta cheese",
  "Chili powder, cumin, and garlic",
  "Chocolate, hazelnut, and cream",
  "Chocolate, raspberry, and cream",
  "Cilantro, lime, and jalapeno",
  "Cinnamon, cloves, and ginger",
  "Cinnamon, nutmeg, and cloves",
  "Cinnamon, sugar, and butter",
  "Coconut, lime, and cilantro",
  "Coconut, lime, and mango",
  "Corn, tomato, and basil",
  "Cornmeal, flour, and buttermilk",
  "Cranberries, orange, and pecans",
  "Cranberry, orange, and ginger",
  "Cranberry, walnut, and blue cheese",
  "Cucumber, avocado, and lime",
  "Cucumber, celery, and lemon",
  "Cucumber, mint, and feta cheese",
  "Cumin, coriander, and paprika",
  "Egg, spinach, and feta cheese",
  "Eggplant, tomato, and mozzarella",
  "Fennel, orange, and olive oil",
  "Fennel, orange, and pomegranate",
  "Feta cheese, cherry tomato, and oregano",
  "Feta cheese, cucumber, and red onion",
  "Figs, prosciutto, and balsamic vinegar",
  "Garlic, ginger, and hoisin sauce",
  "Garlic, lemon, and cumin",
  "Garlic, lemon, and olive oil",
  "Garlic, onion, and bell pepper",
  "Ginger, garlic, and chili paste",
  "Ginger, garlic, and soy sauce",
  "Ginger, honey, and lemon",
  "Gouda cheese, apple, and rosemary",
  "Grape, almond, and blue cheese",
  "Grapefruit, avocado, and shrimp",
  "Green apple, cheddar cheese, and mustard",
  "Green beans, almonds, and lemon zest",
  "Green beans, shallot, and bacon",
  "Green onions, garlic, and ginger",
  "Ham, Swiss cheese, and mustard",
  "Honey, mustard, and thyme",
  "Lamb, rosemary, and garlic",
  "Lemon, basil, and pine nuts",
  "Lemon, garlic, and olive oil",
  "Lemon, garlic, and oregano",
  "Lemon, garlic, and parsley",
  "Lemon, honey, and ginger",
  "Lemon, honey, and rosemary",
  "Lemon, olive oil, and parsley",
  "Lemon, thyme, and garlic",
  "Mango, coconut, and lime",
  "Mango, lime, and chili",
  "Maple syrup, bacon, and pecans",
  "Mushroom, truffle, and Parmesan cheese",
  "Orange, carrot, and ginger",
  "Parmesan cheese, garlic, and breadcrumbs",
  "Parmesan cheese, garlic, and lemon zest",
  "Parmesan cheese, lemon, and black pepper",
  "Peach, basil, and balsamic vinegar",
  "Peach, basil, and goat cheese",
  "Peanut butter, banana, and honey",
  "Peanut butter, soy sauce, and honey",
  "Pear, blue cheese, and arugula",
  "Pear, prosciutto, and arugula",
  "Pear, walnut, and blue cheese",
  "Pecan, goat cheese, and honey",
  "Pecan, maple, and bourbon",
  "Pesto, pine nuts, and Parmesan cheese",
  "Pesto, tomato, and mozzarella",
  "Pineapple, jalapeno, and cilantro",
  "Pistachio, honey, and goat cheese",
  "Pomegranate, orange, and mint",
  "Potato, cheddar cheese, and bacon",
  "Potato, leek, and bacon",
  "Prosciutto, melon, and mint",
  "Quinoa, black beans, and avocado",
  "Quinoa, roasted vegetables, and tahini",
  "Radicchio, pear, and gorgonzola",
  "Radish, cucumber, and feta cheese",
  "Raspberry, brie, and basil",
  "Raspberry, lemon, and white chocolate",
  "Red onion, goat cheese, and arugula",
  "Red pepper, tomato, and basil",
  "Ricotta cheese, basil, and lemon",
  "Roasted vegetables, quinoa, and feta cheese",
  "Sage, onion, and thyme",
  "Salmon, avocado, and wasabi",
  "Salmon, dill, and lemon",
  "Sausage, onion, and bell pepper",
  "Scallions, garlic, and soy sauce",
  "Sesame oil, soy sauce, and honey",
  "Shrimp, garlic, and butter",
  "Shrimp, garlic, and lemon",
  "Spinach, feta cheese, and sun-dried tomatoes",
  "Strawberries, balsamic vinegar, and black pepper",
  "Strawberry, basil, and balsamic vinegar",
  "Sweet potato, black beans, and avocado",
  "Sweet potato, cinnamon, and nutmeg",
  "Sweet potato, kale, and chorizo",
  "Sweet potato, pecan, and marshmallow",
  "Tomato, feta cheese, and olives",
  "Tomato, onion, and cilantro",
  "Tomatoes, basil, and mozzarella",
  "Tuna, avocado, and sesame seeds",
  "Tuna, mayonnaise, and celery",
  "Turmeric, ginger, and coconut milk",
  "Watermelon, feta cheese, and mint",
  "Zucchini, feta cheese, and mint",
  "Zucchini, garlic, and Parmesan cheese",
];
