export const EXAMPLES = [
  "Apples, cinnamon, and caramel",
  "Apricot, almond, and honey",
  "Artichoke, lemon, and garlic",
  "Asparagus, lemon, and parmesan cheese",
  "Avocado, lime, and cilantro",
  "Banana, peanut butter, and chocolate",
  "Basil, tomato, and garlic",
  "Beef, onion, and green pepper",
  "Bell pepper, onion, and garlic",
  "Black beans, corn, and cilantro",
  "Blackberry, mint, and lime",
  "Blueberries, honey, and yogurt",
  "Brown sugar, butter, and vanilla extract",
  "Butternut squash, sage, and brown butter",
  "Caramel, sea salt, and chocolate",
  "Carrots, ginger, and honey",
  "Cherry tomato, mozzarella, and basil pesto",
  "Chicken, mushroom, and thyme",
  "Chickpea, cucumber, and feta cheese",
  "Chocolate, raspberry, and cream",
  "Cilantro, lime, and jalapeno",
  "Corn, tomato, and basil",
  "Cornmeal, flour, and buttermilk",
  "Cranberries, orange, and pecans",
  "Cucumber, mint, and feta cheese",
  "Egg, spinach, and feta cheese",
  "Eggplant, tomato, and mozzarella",
  "Feta cheese, cherry tomato, and oregano",
  "Feta cheese, cucumber, and red onion",
  "Ginger, honey, and lemon",
  "Gouda cheese, apple, and rosemary",
  "Grapefruit, avocado, and shrimp",
  "Green apple, cheddar cheese, and mustard",
  "Green beans, almonds, and lemon zest",
  "Honey, mustard, and thyme",
  "Lamb, rosemary, and garlic",
  "Lemon, garlic, and oregano",
  "Mango, coconut, and lime",
  "Mushroom, truffle, and parmesan cheese",
  "Parmesan cheese, garlic, and breadcrumbs",
  "Peach, basil, and balsamic vinegar",
  "Peanut butter, soy sauce, and honey",
  "Pear, walnut, and blue cheese",
  "Pesto, tomato, and mozzarella",
  "Pineapple, jalapeno, and cilantro",
  "Pistachio, honey, and goat cheese",
  "Pomegranate, orange, and mint",
  "Quinoa, roasted vegetables, and tahini",
  "Radicchio, pear, and gorgonzola",
  "Radish, cucumber, and feta cheese",
  "Raspberry, lemon, and white chocolate",
  "Red pepper, tomato, and basil",
  "Ricotta cheese, basil, and lemon",
  "Roasted vegetables, quinoa, and feta cheese",
  "Sage, onion, and thyme",
  "Salmon, dill, and lemon",
  "Sausage, onion, and bell pepper",
  "Scallions, garlic, and soy sauce",
  "Sesame oil, soy sauce, and honey",
  "Spinach, feta cheese, and sun-dried tomatoes",
  "Sweet potato, kale, and chorizo",
  "Tomatoes, basil, and mozzarella",
  "Tuna, avocado, and sesame seeds",
  "Zucchini, garlic, and parmesan cheese",
];
